config/routes.rb
Maitore::Application.routes.draw do
  devise_for :users

  root :to => 'top#index'
  get '/about'  => 'about#index'
  get '/news'   => 'news#index'
  get '/access' => 'access#index'
  get '/members' => 'members#index'

end

app/models/user.rb
class MailAddressValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors[attribute] << (options[:message] || "is not an email") unless
      value =~ /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  end
end
class User < ActiveRecord::Base
  acts_as_paranoid

  # Include default devise modules. Others available are:
  include ActiveModel::Validations

  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :status, :deleted_at

  before_create :reset_param

  def reset_param
    self.status = 'active'
  end
  # attr_accessible :title, :body
  validates :email, :presence => true, :mail_address => true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/access_controller.rb
class AccessController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include Jpmobile::ViewSelector
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def index
    @users = User.all
    @deleted_users = User.only_deleted
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/about/index.html.erb
<h1>概要</h1>

app/views/access/index.html.erb
<h1>アクセス</h1>

app/views/layouts/_footer.html.erb
&copy; iRubySystems, inc. <%= Time.now.year -%>

app/views/layouts/_footer_mobile.html.erb
<div align='center'>(c)iRubySystems <%= Time.now.year -%></div>

app/views/layouts/_header.html.erb
<%= link_to '刻言道場「まいトレ」', root_url -%>
<% if user_signed_in? %>
<%= current_user.name %>さん /
<%= link_to "サインアウト", destroy_user_session_path, :method => 'delete' %>
<%= link_to "ユーザ情報の編集", edit_user_registration_path %>
<% else %>
<%= link_to "サインイン", new_user_session_path %>
<%= link_to "登録", new_user_registration_path %>
<% end %>

app/views/layouts/_header_mobile.html.erb
<div align='center'>まいトレ</div>

app/views/layouts/_menu.html.erb
<navi>
  <%= link_to '概要', about_url -%>
  <%= link_to 'ニュース', news_url -%>
</navi>

app/views/layouts/_menu_mobile.html.erb
&#xe6e2;<%= link_to 'トップページ', root_url, {:accesskey => '1'} -%><br />
&#xe6e3;<%= link_to '概要', about_url, {:accesskey => '2'} -%><br />
&#xe6e4;<%= link_to 'ニュース', news_url, {:accesskey => '3'} -%><br />
&#xe6e5;<%= link_to 'アクセス', access_url, {:accesskey => '4'} -%><br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8' />
  <meta name='viewport' content='width=device-width,
    user-scalable=yes,initial-scale=1.0,maximum-scale-3.0' />
  <title>Maitore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render :partial => 'layouts/header' -%>
  </header>
  <div id='wrapper'>
    <navi>
      <%= render :partial => 'layouts/menu' -%>
    </navi>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <section>
      <%= yield %>
    </section>
    <div id='clear'></div>
  </div>
  <hr>
  <footer>
    <%= render :partial => 'layouts/footer' -%>
  </footer>

</body>
</html>

app/views/layouts/application_mobile.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maitore</title>
</head>
<body>
  <%= render :partial => 'layouts/header' -%>
  <%= yield %>
  <%= render :partial => 'layouts/menu' -%>
  <%= render :partial => 'layouts/footer' -%>
</body>
</html>

app/views/members/index.html.erb
<h1>メンバー一覧</h1>
<p>現存ユーザ</p>
<ul>
<% @users.each do |user| %>
<li><%= user.id %>:<%= user.name %>(<%= user.status %>)</li>
<% end %>
</ul>

<p>削除ユーザ</p>
<ul>
<% @deleted_users.each do |user| %>
<li><%= user.id %>:<%= user.name %>(<%= user.status %>)</li>
<% end %>
</ul>

app/views/news/index.html.erb
<h1>ニュース</h1>

app/views/top/index.html.erb
<h1>ようこそ</h1>
<p>Find me in app/views/top/index.html.erb</p>

app/views/users/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "サインイン", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "パスワード忘れ?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>